In [1]:
#导入第三方库
import torch #pytorch框架
import pandas as pd #数据集读入库
import matplotlib.pyplot as plt #绘制图表
import torch.nn as nn #模型中的网络层使用
from torch import optim #优化器使用
from torch.utils.data import DataLoader, TensorDataset #数据集处理
from sklearn.model_selection import  train_test_split #数据划分
import numpy as np

In [2]:
#读取文件
movies_df = pd.read_csv("./movies.csv")
ratings_df = pd.read_csv("./ratings.csv")
tags_df = pd.read_csv("./tags.csv")

In [3]:
ratings_df=ratings_df.drop(columns=['timestamp'])
tags_df=tags_df.drop(columns=['timestamp'])
movies_ratings_df=pd.merge(movies_df,ratings_df,on='movieId')
movies_ratings_tags_df=pd.merge(movies_ratings_df,tags_df,on=['movieId','userId'],how='outer')
movies_ratings_tags_df=movies_ratings_tags_df.dropna(subset=['rating', 'title','userId','genres','movieId'])
movies_ratings_tags_df['tag'] = movies_ratings_tags_df['tag'].fillna('noTags')
encoding = {'noTags': 0}
unique_values = set(movies_ratings_tags_df['tag']) - set(encoding.keys())
for i, value in enumerate(unique_values, start=1):
    encoding[value] = i
movies_ratings_tags_df['tag'] = movies_ratings_tags_df['tag'].map(encoding)
genres_split = movies_ratings_tags_df['genres'].str.get_dummies('|')  #使用get_dummies这个方法将genres这一列的数据分割出来形成新的特征列
movies_ratings_tags_df = pd.concat([movies_ratings_tags_df, genres_split], axis=1)# 将新生成的列与原始数据合并
movies_ratings_tags_df=movies_ratings_tags_df.drop(columns=["genres"])

In [4]:
movies_ratings_tags_df

,movieId,title,userId,rating,tag,(no genres listed),Action,Adventure,Animation,Children,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),1,4.0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,Toy Story (1995),5,4.0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,Toy Story (1995),7,4.5,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,Toy Story (1995),15,2.5,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,1,Toy Story (1995),17,4.5,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102672,193581,Black Butler: Book of the Atlantic (2017),184,4.0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
102673,193583,No Game No Life: Zero (2017),184,3.5,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
102674,193585,Flint (2017),184,3.5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
102675,193587,Bungo Stray Dogs: Dead Apple (2018),184,3.5,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
102676,193609,Andrew Dice Clay: Dice Rules (1991),331,4.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0